# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0002_auto_20170218_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Description',
            new_name='Desc',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='desc',
        ),
    ]
