# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0003_auto_20170219_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
