# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0005_auto_20170219_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycourses.Desc'),
        ),
    ]
