# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0006_auto_20170219_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(max_length=50),
        ),
    ]
