# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0007_auto_20170219_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mycourses.Desc'),
        ),
    ]
