# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0008_auto_20170219_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
        migrations.AddField(
            model_name='desc',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycourses.Course'),
        ),
    ]
