# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourses', '0009_auto_20170219_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='desc',
            name='desc',
            field=models.TextField(default='this is desc'),
        ),
    ]
